### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by xicoxicao** [Tgxcorporation/skin.blackglassnova#12]
Hi

I tried to install this skin but got the following errors:

15:04:47.041 T:199672   ERROR: CCurlFile::Open failed with code 404 for http://legionworldtv.com/freeworld/repo/resource.images.recordlabels.white/resource.images.recordlabels.white-0.0.7.zip
15:04:47.041 T:199672   ERROR: CAddonInstallJob[resource.images.recordlabels.white]: failed to download special://home/addons/packages/resource.images.recordlabels.white-0.0.7.zip
15:04:47.043 T:199672   ERROR: CAddonInstallJob[skin.blackglassnova]: failed to install dependency resource.images.recordlabels.white

Looking at the web address indicated, that file is not available, and without it I cannot finish the install.

Pls. informe how I can get around this issue

Thanks

**Comment by Tgxcorporation** [comment]
Manually download the missing addons from:

http://mirrors.kodi.tv/addons/

And manually install them using the addon browser in Kodi.

Tgx
