### ISSUE TITLE
Dependency issue: XBMC.GUI 5.13

### ISSUE THREAD

**Issue by Cyber5imon** [Tgxcorporation/skin.blackglassnova#16]
After upgrading to 18 RC5 (Ubuntu), Black Glass Nova will not install and gives an error: 
The dependency on xbmc.gui version 5.13.0 could not be satisfied.

It appears this just started with RC5.

**Comment by Cyber5imon** [comment]
Changing the dependency to 5.14.0 in the addon.xml file fixes the issue...

**Comment by dawsonjw** [comment]
Hi,  Have the same issue running under Windows 10.  Is it safe to change this without screwing something up?  I noticed that the install programs updates the videos database to the next version.

Further do you think the problem needs a fix from Kodi's end or is it the skin developer?

Oh, can't find the addon.xml file.  Where is that located.

cheers

John

**Comment by Tgxcorporation** [comment]
I’m going to post an update for the final Leia version

**Comment by dawsonjw** [comment]
Hi,
    thanks for that.  Oh, BTW not sure if you know but the right hand scroll bar (fast page scrolling) does not always appear when listing Movies / TV shows etc.

cheers

John

**Comment by Tgxcorporation** [comment]
I know. I’ve already tried but the code is ok. I think it might be an issue with the Kodi skin engine.

Tgx

**Comment by Tgxcorporation** [comment]
The skin is now fully working with Leia final.
