### ISSUE TITLE
Timers day of week problems in Kodi 16.0 RC2

### ISSUE THREAD

**Issue by DavidBiesack** [Tgxcorporation/skin.blackglassnova#2]
I installed Kodi 16.0 RC 2 and this skin has a usability problem.

When I try to add a recording from the guide, or manually add a new time, the UI for selecting the days of the week is messed up and does not show the selection.

For example when I tried to add a new timer for 9:00 PM on Sunday, I selected Days of Week and I was presented with a window listing Monday through Sunday. I clicked on Sunday and clicked OK and the timer show MO-TU-WE-TH-FR-SA-__ It looks like it selected all days except Sunday rather than selecting the day I clicked!

I clicked again to edit and as I clicked each day, there was no indication if the day was selected or not. It seems like these buttons act like toggles, but there is no UI indication as to if the day is selected or not until you close the dialog.

I'm using Black Glass Nova skin. I run Kodi on Windows 10 with NextPVR as my backend.

**Comment by Tgxcorporation** [comment]
Is it working ok with the Confluence skin?

**Comment by DavidBiesack** [comment]
yes. The "buttons" change color when selected or deselected.

**Comment by Tgxcorporation** [comment]
Ok. I think NextPvr support radically changed with Jarvis. 
Exit Kodi. Go into your "%appdata%\kodi\addons\skin.blackglassnova\1080i" folder and delete the "RecordPrefs.xml" file. Start Kodi and try again.

**Comment by Tgxcorporation** [comment]
Maybe it's better to save the file somewhere else, just for backup purpose.

**Comment by DavidBiesack** [comment]
I tried that but it did not fix the problem.
I also uninstalled the skin, closed Kodi, then reinstalled it and the problem is still there.

**Comment by Tgxcorporation** [comment]
Today i'm installing and testing what is happening with NextPvr

**Comment by Tgxcorporation** [comment]
Ok, now i can understand your issue.
This is what is happening.
The skin uses the white color to show selected items. 
Unselected items are shown in light grey. There's a subtle difference.
When you open the dialog diplaying the days of the week, all the days are already selected and all in white bright color. If you click on sunday, then sunday is getting unselected and will get the light grey color. That's the reason of your issue.

**Comment by DavidBiesack** [comment]
I can see the difference. thanks. It's a bit too subtle for me... more contrast would be better.

**Comment by Tgxcorporation** [comment]
The problem is to find a color that does not clash with the skin color themes.
I'll try for the next release.
