### ISSUE TITLE
BGN,,,SPLASH SCREEN,,,,and Kodi logo removal

### ISSUE THREAD

**Issue by switchtv** [Tgxcorporation/skin.blackglassnova#3]
After weeks of wrestling the Titan Skin,,,I have now moved to use the BGN

equally as nice,,wish it had as much customization as Titan,

having said that

PROBLEM 1
can i remove the KODI logo from the left top corner,,,its annoying to me

PROBLEM 2

is  there a way to  delete the BGN Splash screen,,,when Kodi opens

it is not a PNG file,,,in media folder,,,where other skins store them

gREAT WORK..THANK YOU IN ADVANCE

**Comment by Tgxcorporation** [comment]
1 - https://github.com/Tgxcorporation/skin.blackglassnova/blob/master/1080i/Home.xml#L115
2 - https://github.com/Tgxcorporation/skin.blackglassnova/blob/master/1080i/Startup.xml#L75 and https://github.com/Tgxcorporation/skin.blackglassnova/blob/master/1080i/Startup.xml#L83

**Comment by switchtv** [comment]
Massimo,,,thank you so much for this information

I take it i must edit the xml file within Kodi

can you suggest an editir that works,,,,and where.how to i gain access to
this Kodi file?

thanks once again
richard

**Comment by Tgxcorporation** [comment]
You basically need a text editor such as Notepad++ (only Windows) or SublimeText (multi platform).
There's no specific editor for skin files.
