### ISSUE TITLE
Unable to customize submenu backgrounds

### ISSUE THREAD

**Issue by aidalgol** [Tgxcorporation/skin.blackglassnova#4]
Changing the background for home menu items does not change the background displayed in that submenu.  For example, if I change the background image for the "TV shows" home-menu item, my custom background is displayed when I select the menu item "TV shows" on the home menu, but the default fanart is still displayed when I _enter_ the "TV shows" menu.

**Comment by Tgxcorporation** [comment]
You need to use the Backgrounds section in skin settings for the backgrounds to be set in the whole skin.
Backgrounds in the home menu editor apply only to the home menu.

Tgx

**Comment by aidalgol** [comment]
Ah, yes, that does work as expected.  I did see that item in the settings menu, but I somehow missed the widget that lets you select the background to change.  Sorry for the noise!
