### ISSUE TITLE
no OSD when changing channels with up/down keys

### ISSUE THREAD

**Issue by drwyrm** [Tgxcorporation/skin.blackglassnova#5]
There is no OSD when changing channels with up/down keys. This makes it hard when using "press enter to change channel" option or delay when changing channels.

I can work around this by pressing INFO before changing channels, but it's annoying, it would be nice to have the OSD auto open when pressing up/down.

**Comment by Tgxcorporation** [comment]
If you refer to the missing info box when changing channel, it's fixed in the latest commit for Krypton.
This is together with a general revision and simplification of the Video OSD.
The skin now behaves exactly like the default skin.

Thanks

Tgx

**Comment by drwyrm** [comment]
Yes, that's what I meant. Thanks for fixing it :)
