### ISSUE TITLE
Custom Menu in 6.0 

### ISSUE THREAD

**Issue by decosse** [Tgxcorporation/skin.blackglassnova#6]
Just installed kodi 17.0 beta 1 and installed BGN v 6.0 from the git here. 

Having problems with the customization elements of v6.0  

Adding a new Main Menu item - this works if selecting an action from the Programs menu; 
However if you attempt to add a shortcut to a Video Addon item, it seems to successfully populate the icon (and even automatically loads that addon's own graphic) but the main menu item will simply not execute - does nothing when you click on the icon (or 'enter' with it highlighted); I tried this with several Program Addons (which worked) and even more Video Addons (none of which worked) 

The same thing happens with a sub-menu item; for example, under my 'Favourites' main menu item, it already showed the sub-menu items I was already using in v 5.5, with the correct links appropriate for them; again, clicking the sub-menu item fails to launch (indeed does not do anything). 
To that same main menu item (Favourites in this case) I added another, new sub-menu item from the programs list - that one will launch, while the other items alongside it, do nothing. 
i.e. Similar to the main menu, any shortcut associated with a video add-on (whether an addon direct launch, or a sub-menu item within a particular add-on) will not activate, while one from a program add-on will. 

Hope that all makes sense and you have some time to take a look at that. Please advise if you need further information or tests you would like me to try.

**Comment by Tgxcorporation** [comment]
I've just tried the same steps you described and on my system everything is ok.

Which version of the script.skinshortcuts are you using? Mine is 1.0.10.

Have you tried to reset the home menu to defaults and start from scratch?

Thanks

Tgx

**Comment by decosse** [comment]
Thanks for your quick response 
Sorry - Where do I find that script-skinshortcuts version? 

My upgrade process (this particular one is a Windows machine - my testbed) was to simply to initially change back to Confluence, install the 17 beta (over 16.1) and then install the BGN v6.0 from the zipfile. 

I have tried reloading the 17 beta (but did not delete current version) and no difference. 

I have not yet reset the menu to default but can try that.

**Comment by Tgxcorporation** [comment]
This is the latest version of the script.skinshortcuts addon: https://github.com/BigNoid/script.skinshortcuts/archive/master.zip

Install it from the addon browser - install from zip file.

I think the issue you are having is because in Krypton a lot of window names have changed and the old addons are not working properly anymore.

**Comment by decosse** [comment]
Excellent - thank you! 
I first tried resetting the default & re-addressing my custom menu - no difference; 
but installing that script.skinshortcuts immediately resolved it. 

Why would the version in the Beta 'not' be at the latest version? ???? 

Much appreciated! I am SOOO pleased to be able to continue using your awesome skin - it's comfortable and 'fits' well :)

**Comment by Tgxcorporation** [comment]
Glad everything is ok!
