### ISSUE TITLE
When localization (hun) is missing no text is shown, only the switch (yes/no) appears

### ISSUE THREAD

**Issue by pzsapa** [Tgxcorporation/skin.blackglassnova#8]
I guess when localization (hun) is missing no text is shown. I think an empty string is shown. In this case only the switch (yes/no) appears in settings menu and it makes difficult to find out what this settings item is about. It might only be an issue on exotic languages like mine (Hungarian), but would be helpful if the original English text will appear in this case. Now, my only solution is to change back the language to English in order to see the text of certain settings items. 
I think I use the latest version for Kodi 17.0

**Comment by Tgxcorporation** [comment]
Localization was working in Jarvis?

**Comment by Tgxcorporation** [comment]
I've just installed the Hungarian language and switched to Black Glass Nova. Krypton 17.1. It seems to work, some labels are in English:

![schermata-2017-04-06-alle-10 11 09- 2](https://cloud.githubusercontent.com/assets/1019037/24744228/8f4ae928-1ab1-11e7-98db-af928c3883ab.jpg)

**Comment by pzsapa** [comment]
As I remember it was ok at first time to me as well. But after it
disappeared more than half of options and never shown again. Would you quit
and come back again? If it works for you please close the issue. In that
case something unique happens with my system.

Thanks for checking,
pzsapa

**Comment by Tgxcorporation** [comment]
It's working here. Sorry. Cannot help. 
I think you'd better start with a clean Kodi installation.

Tgx

**Comment by pzsapa** [comment]
Ok, thanks
